# Generated by Django 4.1.5 on 2023-05-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_class_options_remove_class_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacher',
            options={'verbose_name_plural': 'Students & Teachers'},
        ),
    ]
