# Generated by Django 4.1.5 on 2023-05-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_reservation_delete_studentteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
