# Generated by Django 4.1.5 on 2023-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_class_student_remove_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_length',
            field=models.CharField(choices=[('30 min', '30 min'), ('45 min', '45 min'), ('60 min', '60 min')], default='30 min', max_length=30),
        ),
    ]
