# Generated by Django 4.1.5 on 2023-05-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_class_class_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
    ]
